local km = vim.keymap.set

km('n', '<A-S-h>', '<C-w>h', { desc = 'Move focus to the left window' })
km('n', '<A-S-j>', '<C-w>j', { desc = 'Move focus to the lower window' })
km('n', '<A-S-k>', '<C-w>k', { desc = 'Move focus to the upper window' })
km('n', '<A-S-l>', '<C-w>l', { desc = 'Move focus to the right window' })
km('n', '<C-b>', '<C-b>zz', { desc = 'Center after full page scroll up' })
km('n', '<C-d>', '<C-d>zz', { desc = 'Center after half page scroll down' })
km('n', '<C-f>', '<C-f>zz', { desc = 'Center after full page scroll down' })
km('n', '<C-j>', '<cmd>cprev<CR>zz', { desc = 'Prev quickfix' })
km('n', '<C-k>', '<cmd>cnext<CR>zz', { desc = 'Next quickfix' })
km('n', '<C-u>', '<C-u>zz', { desc = 'Center after half page scroll up' })
km('n', '<Esc>', '<cmd>nohlsearch<CR>', { desc = 'Highlight on search. Clear with <Esc>' })
km('n', '<leader><C-a>', 'ggVG', { desc = 'Select [A]ll' })
km('n', '<leader><C-j>', '<cmd>lprev<CR>zz', { desc = 'Prev location' })
km('n', '<leader><C-k>', '<cmd>lnext<CR>zz', { desc = 'Next location' })
km('n', '<leader>P', [["+P]], { desc = '[P] Paste from system clipboard' })
km('n', '<leader>Q', 'q', { desc = '[q] Macro' })
km('n', '<leader>Y', [["+Y]], { desc = '[Y] Yank into system clipboard' })
km('n', '<leader>e', vim.diagnostic.open_float, { desc = 'Show diagnostic [E]rror messages' })
km('n', '<leader>jk', vim.cmd.Ex, { desc = '[j]ump bac[k]' })
km('n', '<leader>q', vim.diagnostic.setloclist, { desc = 'Open diagnostic [Q]uickfix list' })
km('n', '<leader>r', [[:%s/\<<C-r><C-w>\>/<C-r><C-w>/gI<Left><Left><Left>]], { desc = 'Substitute word' })
km('n', 'J', 'mzJ`z', { desc = 'Join next line' })
km('n', 'N', 'Nzzzv', { desc = 'Center after prev search result' })
km('n', 'Q', 'ZQ', { desc = 'Quit without saving' })
km('n', '[d', vim.diagnostic.goto_prev, { desc = 'Go to previous [D]iagnostic message' })
km('n', ']d', vim.diagnostic.goto_next, { desc = 'Go to next [D]iagnostic message' })
km('n', 'n', 'nzzzv', { desc = 'Center after next search result' })
km('n', 'q', ':q<CR>', { desc = 'Quit' })
km('t', '<Esc><Esc>', '<C-\\><C-n>', { desc = 'Exit terminal mode' })
km('v', 'J', ":m '>+1<CR>gv=gv", { desc = 'Move highlight up' })
km('v', 'K', ":m '<-2<CR>gv=gv", { desc = 'Move highlight down' })
km({ 'n', 'v' }, '<leader>d', [["_d]], { desc = '[d] Delete into void' })
km({ 'n', 'v' }, '<leader>f', vim.lsp.buf.format, { desc = '[f] Format' })
km({ 'n', 'v' }, '<leader>p', [["+p]], { desc = '[p] Paste from system clipboard' })
km({ 'n', 'v' }, '<leader>y', [["+y]], { desc = '[y] Yank into system clipboard' })
