vim.g.have_nerd_font = true
vim.g.netrw_banner = 0
vim.g.netrw_liststyle = 3 -- Tree view
vim.opt.backup = false -- Use undo file
vim.opt.breakindent = true -- Enable break indent
vim.opt.colorcolumn = '100'
vim.opt.cursorline = true -- Show which line your cursor is on
vim.opt.expandtab = true -- Insert X number of spaces with tab
vim.opt.hlsearch = true -- Highlight on search. Clear with <Esc>
vim.opt.ignorecase = true -- Case-insensitive search unless \C or capital in search
vim.opt.inccommand = 'split' -- Preview subtitutions while typing
vim.opt.list = true -- Sets how neovim will display certain whitespace in the editor.
vim.opt.listchars = { tab = '» ', trail = '·', nbsp = '␣' } -- NBSP: non-breaking space. Space where a linebreak is prevented
vim.opt.mouse = 'a' -- Enable mouse
vim.opt.number = true -- Line numbers
vim.opt.relativenumber = true -- Relative line numbers
vim.opt.scrolloff = 10 -- Minimal number of screen lines to keep above and below the cursor.
vim.opt.shiftwidth = 4 -- Number of spaces in auto-indentation
vim.opt.showmode = false -- Don't show mode. It's already in Mini's status line
vim.opt.signcolumn = 'yes' -- Sign column in left (can be used for git, etc.)
vim.opt.smartcase = true -- Case-insensitive search unless \C or capital in search
vim.opt.smartindent = true
vim.opt.softtabstop = 4 -- Insert X number of spaces with tab
vim.opt.splitbelow = true -- Configure how new splits should be opened
vim.opt.splitright = true -- Configure how new splits should be opened
vim.opt.swapfile = false -- Use undo file
vim.opt.tabstop = 4 -- Insert X number of spaces with tab
vim.opt.termguicolors = true
vim.opt.timeoutlen = 300 -- MS wait for which-key and a possible multi-key mapping
vim.opt.undodir = os.getenv 'USERPROFILE' .. '/.vim/undodir' -- Use undo file
vim.opt.undofile = true -- Use undo file
vim.opt.updatetime = 250 -- MS to wait before triggering Cursor auto-commands (LSP, etc.)
vim.opt.wrap = false -- Disable line wrapping
